# Generated by Django 4.1.4 on 2023-02-04 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_control', '0002_verifycode_code_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 3, 1, 51, 9, 434892, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
