# Generated by Django 4.1.4 on 2023-02-04 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_control', '0006_alter_verifycode_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 6, 53, 13, 455927, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
