# Generated by Django 4.1.4 on 2023-02-13 21:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_control', '0019_alter_verifycode_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('sub_type', models.CharField(choices=[('new_function', 'New Function')], default='verify_email', max_length=20)),
                ('sub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'subscription_email',
                'verbose_name_plural': 'subscription_email',
                'ordering': ['-sub_time'],
            },
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 13, 22, 2, 53, 248762, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
