# Generated by Django 4.1.4 on 2023-02-27 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_control', '0026_alter_verifycode_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 20, 20, 44, 128480, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
