# Generated by Django 4.1.4 on 2023-02-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(editable=False, max_length=150)),
                ('name', models.CharField(default=None, max_length=200)),
                ('owner', models.CharField(default=None, max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created_time',),
            },
        ),
    ]
