# Generated by Django 4.1.4 on 2023-02-03 20:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=150)),
                ('name', models.CharField(default=None, max_length=200)),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('disable', 'Disable'), ('enable', 'Enable')], default='enable', max_length=50)),
                ('suc_conv_num', models.PositiveIntegerField(default=0)),
                ('failed_conv_num', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 2, 20, 45, 54, 988607, tzinfo=datetime.timezone.utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created_time',),
            },
        ),
    ]
