# Generated by Django 4.1.4 on 2023-02-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('disable', 'Disable'), ('enable', 'Enable')], default='enable', max_length=50),
        ),
    ]
