# Generated by Django 4.1.4 on 2023-02-03 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0002_alter_apikey_expiration_time_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 2, 16, 19, 8, 545796, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
