# Generated by Django 4.1.4 on 2023-02-03 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0003_alter_apikey_expiration_time_alter_apikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='failed_conv_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apikey',
            name='suc_conv_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 2, 16, 36, 6, 497588, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
