# Generated by Django 4.1.4 on 2023-02-03 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0004_apikey_failed_conv_num_apikey_suc_conv_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 2, 18, 57, 18, 225649, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
