# Generated by Django 4.1.4 on 2023-02-06 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0012_alter_apikey_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 6, 0, 42, 964525, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
