# Generated by Django 4.1.4 on 2023-02-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devices_device_type_alter_devices_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('disable', 'Disable')], default='inactive', max_length=50),
        ),
    ]
