# Generated by Django 4.1.4 on 2023-02-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_devices_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='last_login_time',
            new_name='last_online',
        ),
    ]
