# Generated by Django 4.1.4 on 2023-02-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_devices_status_devices_activated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='activated',
            new_name='is_activated',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='enable',
            new_name='is_enable',
        ),
    ]
