# Generated by Django 4.1.4 on 2023-02-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_rename_activated_devices_is_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
