# Generated by Django 4.1.4 on 2023-02-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_remove_performance_disk_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='cpu',
            new_name='cpu_rate',
        ),
    ]
