# Generated by Django 4.1.4 on 2023-02-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
    ]
