# Generated by Django 4.1.7 on 2023-04-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
