# Generated by Django 4.1.4 on 2023-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersettings_alter_users_is_staff_delete_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='style_mode',
            field=models.SmallIntegerField(choices=[('dark', 'dark'), ('light', 'light')], default='dark'),
        ),
    ]
