# Generated by Django 4.1.4 on 2023-02-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usersettings_style_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'usersettings', 'verbose_name_plural': 'usersettings'},
        ),
    ]
