# Generated by Django 4.1.4 on 2023-02-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usersettings_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
