# Generated by Django 4.1.7 on 2023-04-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='phone'),
        ),
    ]
