# Generated by Django 4.1.7 on 2023-04-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Oauth-id'),
        ),
    ]
