# Generated by Django 4.1.7 on 2023-04-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_loginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='login_device',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='browser_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='device_os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='is_mobile',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='is_pc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
