# Generated by Django 4.1.7 on 2023-04-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loginhistory_device_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_tablet',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
