# Generated by Django 4.1.4 on 2023-02-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='oauth_page_url',
        ),
    ]
