# Generated by Django 4.1.4 on 2023-02-03 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 2, 23, 41, 19, 622856, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
