# Generated by Django 4.1.4 on 2023-02-13 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0016_alter_apikey_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 12, 16, 7, 40, 922510, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
