# Generated by Django 4.1.4 on 2023-02-04 01:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 3, 1, 13, 51, 100707, tzinfo=datetime.timezone.utc), null=True)),
            ],
            options={
                'verbose_name': 'verify_code',
                'verbose_name_plural': 'verify_code',
                'ordering': ['-send_time'],
            },
        ),
    ]
