# Generated by Django 4.1.4 on 2023-02-04 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='code_type',
            field=models.CharField(choices=[('register', 'Register')], default='register', max_length=20),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 3, 1, 15, 59, 869303, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
