# Generated by Django 4.1.4 on 2023-02-04 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_control', '0003_alter_verifycode_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code_type',
            field=models.CharField(choices=[('verify_email', 'verify_email'), ('reset_password', 'reset_password')], default='verify_email', max_length=20),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 5, 39, 52, 237671, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
