# Generated by Django 4.1.6 on 2023-02-13 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_control', '0011_alter_verifycode_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 13, 2, 47, 40, 599884, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
