# Generated by Django 4.1.4 on 2023-03-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_eventlog_action_eventlog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
