# Generated by Django 4.1.7 on 2023-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'Mode 1'), (1, 'Mode 1'), (1, 'Mode 1'), (1, 'Mode 1')], default=1)),
            ],
            options={
                'verbose_name': 'system_setting',
                'verbose_name_plural': 'system_setting',
            },
        ),
    ]
