# Generated by Django 4.1.7 on 2023-03-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Shutdown', 'Shutdown'), ('Restart', 'Restart'), ('Other', 'Other')], default='1', max_length=50)),
                ('message', models.TextField(default=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices')),
            ],
            options={
                'verbose_name': 'operation_log',
                'verbose_name_plural': 'operation_log',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(1, 'Event1'), (2, 'Event2'), (3, 'Event3'), (4, 'Event4')], default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, default='devices/log_img/test.jpg', null=True, upload_to='devices/log_img')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices')),
            ],
            options={
                'verbose_name': 'eventlog',
                'verbose_name_plural': 'eventlog',
                'ordering': ('-created_time',),
            },
        ),
    ]
