# Generated by Django 4.1.7 on 2023-03-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='image_url',
            field=models.FileField(blank=True, default='devices/log_img/test.jpg', null=True, upload_to='devices/log_img'),
        ),
    ]
