# Generated by Django 4.1.7 on 2023-03-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlog',
            old_name='image_url',
            new_name='resource_url',
        ),
    ]
