# Generated by Django 4.1.4 on 2023-02-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_devices_is_enable'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('1', 'Event1'), ('2', 'Event2'), ('3', 'Event3'), ('4', 'Event4')], default='1', max_length=50)),
                ('message', models.TextField(default=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices')),
            ],
            options={
                'verbose_name': 'SurveillanceLog',
                'verbose_name_plural': 'SurveillanceLog',
                'ordering': ('-created_time',),
            },
        ),
        migrations.DeleteModel(
            name='SurveillanceLog',
        ),
    ]
