# Generated by Django 4.1.4 on 2023-02-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_eventlog_delete_surveillancelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ('-created_time',), 'verbose_name': 'EventLog', 'verbose_name_plural': 'EventLog'},
        ),
    ]
