# Generated by Django 4.1.7 on 2023-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_rename_image_url_eventlog_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='resource_type',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
