# Generated by Django 4.1.4 on 2023-02-21 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_devices_is_enable'),
        ('record', '0003_alter_eventlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ('-created_time',), 'verbose_name': 'eventlog', 'verbose_name_plural': 'eventlog'},
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Shutdown', 'Shutdown'), ('Restart', 'Restart'), ('Other', 'Other')], default='1', max_length=50)),
                ('message', models.TextField(default=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices')),
            ],
            options={
                'verbose_name': 'operationlog',
                'verbose_name_plural': 'operationlog',
                'ordering': ('-created_time',),
            },
        ),
    ]
