# Generated by Django 4.1.4 on 2023-03-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_eventlog_options_operationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event',
            field=models.IntegerField(choices=[(1, 'Event1'), (2, 'Event2'), (3, 'Event3'), (4, 'Event4')], default=1),
        ),
    ]
