# Generated by Django 4.1.4 on 2023-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_eventlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='action',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='image_url',
            field=models.ImageField(blank=True, default='devices/log_img/test.jpg', null=True, upload_to='devices/log_img'),
        ),
    ]
