# Generated by Django 4.1.7 on 2023-03-09 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('motion_detect', 'MotionDetect'), ('gateway', 'Gateway')], default='motion detect', max_length=200)),
                ('device_type', models.CharField(choices=[('raspberry_pi', 'Raspberry Pi')], default='Raspberry Pi', max_length=200)),
                ('api_key', models.CharField(editable=False, max_length=150)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_enable', models.BooleanField(default=True)),
                ('protocol', models.CharField(choices=[('HTTP', 'HTTP')], default='HTTP', max_length=50)),
                ('sdk', models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('C', 'C')], default='Python', max_length=50)),
                ('suc_conv_num', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'devices',
                'verbose_name_plural': 'devices',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_rate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('mem_rate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('disk_write_io', models.IntegerField(default=0)),
                ('disk_read_io', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices')),
            ],
            options={
                'verbose_name': 'performance',
                'verbose_name_plural': 'performance',
                'ordering': ('-created_time',),
            },
        ),
    ]
