# Generated by Django 4.1.6 on 2023-02-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_type',
            field=models.CharField(choices=[('Raspberry Pi', 'Raspberry Pi')], default='Raspberry Pi', max_length=200),
        ),
        migrations.AddField(
            model_name='devices',
            name='protocol',
            field=models.CharField(choices=[('HTTP', 'HTTP')], default='HTTP', max_length=50),
        ),
        migrations.AddField(
            model_name='devices',
            name='sdk',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('C', 'C')], default='Python', max_length=50),
        ),
    ]
