# Generated by Django 4.1.7 on 2023-03-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='protocol',
            field=models.CharField(choices=[('Websocket', 'Websocket')], default='HTTP', max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='disk_read_io',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='disk_write_io',
            field=models.BigIntegerField(default=0),
        ),
    ]
