# Generated by Django 4.1.4 on 2023-02-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_last_login_time_devices_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('inactivated', 'Inactivated'), ('active', 'Active'), ('disable', 'Disable')], default='inactivated', max_length=50),
        ),
    ]
