# Generated by Django 4.1.4 on 2023-02-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_devices_is_enable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='api_key',
            new_name='device_key',
        ),
    ]
