# Generated by Django 4.1.4 on 2023-02-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_rename_api_key_devices_device_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='device_key',
            new_name='api_key',
        ),
    ]
