# Generated by Django 4.1.4 on 2023-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_devices_options_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='disk_rate',
        ),
        migrations.AddField(
            model_name='performance',
            name='disk_read_io',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='disk_write_io',
            field=models.IntegerField(default=0),
        ),
    ]
