# Generated by Django 4.1.7 on 2023-03-04 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('sub_type', models.CharField(choices=[('new_function', 'New Function')], default='verify_email', max_length=20)),
                ('sub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'subscription_email',
                'verbose_name_plural': 'subscription_email',
                'ordering': ['-sub_time'],
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('code_type', models.CharField(choices=[('verify_email', 'verify_email'), ('reset_password', 'reset_password')], default='verify_email', max_length=20)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'verify_code',
                'verbose_name_plural': 'verify_code',
                'ordering': ['-send_time'],
            },
        ),
    ]
